# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ea9d4c04843b7938c12fb8246e4ed63c76ddd4280bf96ad51b8ba2d071180c5382162746668e618b2d85db6d61eaae96bb5dc00982bc46d9153f9745df143020

test:
  secret_key_base: b4f96ba707dec14515a0abfe2a69496620c9674d9c7e9b310de3ef0dcfaab88cba68c41a8905f89b2f0d2b919ad19d66d4c056c0fdf0477a60a16435652d9559

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
